# Generated by Django 4.2.7 on 2023-11-11 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_number', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.IntegerField()),
                ('q1a', models.CharField(default='N', max_length=2)),
                ('q1b', models.CharField(default='N', max_length=2)),
                ('q1c', models.CharField(default='N', max_length=2)),
                ('q1d', models.CharField(default='N', max_length=2)),
                ('q2a', models.CharField(default='N', max_length=2)),
                ('q2b', models.CharField(default='N', max_length=2)),
                ('q2c', models.CharField(default='N', max_length=2)),
                ('q2d', models.CharField(default='N', max_length=2)),
                ('q3a', models.CharField(default='N', max_length=2)),
                ('q3b', models.CharField(default='N', max_length=2)),
                ('q3c', models.CharField(default='N', max_length=2)),
                ('q3d', models.CharField(default='N', max_length=2)),
                ('q1_total', models.IntegerField(default=0)),
                ('q2_total', models.IntegerField(default=0)),
                ('q3_total', models.IntegerField(default=0)),
                ('q1_letter', models.CharField(default='N0', max_length=2)),
                ('q2_letter', models.CharField(default='N0', max_length=2)),
                ('q3_letter', models.CharField(default='N0', max_length=2)),
                ('total_score', models.IntegerField(default=0)),
                ('paper_submitted', models.BooleanField(default=False)),
                ('marking_created', models.DateTimeField(auto_now_add=True)),
                ('marking_updated', models.DateTimeField(auto_now=True)),
                ('paper_void', models.BooleanField(default=False)),
                ('check_marker', models.CharField(default='', max_length=20)),
                ('check_marked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_marker', models.BooleanField(default=False)),
                ('standard', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='standard', to='marking.standard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cutscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.IntegerField(default=7)),
                ('merit', models.IntegerField(default=14)),
                ('excellence', models.IntegerField(default=19)),
                ('standard', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cutscore_standard', to='marking.standard')),
            ],
        ),
    ]
