# Generated by Django 4.2.7 on 2023-11-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0002_standard_q1a_type_standard_q1b_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='q1a_type',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='q1b_type',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='q1c_type',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='q1d_type',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='q2a_type',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='q2b_type',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='q2c_type',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='q2d_type',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='q3a_type',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='q3b_type',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='q3c_type',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='q3d_type',
        ),
        migrations.AddField(
            model_name='standard',
            name='q1_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AMME+', 'AMME+')], default='AMME', max_length=5),
        ),
        migrations.AddField(
            model_name='standard',
            name='q2_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AMME+', 'AMME+')], default='AMME', max_length=5),
        ),
        migrations.AddField(
            model_name='standard',
            name='q3_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AMME+', 'AMME+')], default='AMME', max_length=5),
        ),
    ]
