# Generated by Django 4.2.7 on 2023-11-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0003_remove_standard_q1a_type_remove_standard_q1b_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='q1_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AEEM', 'AEEM')], default='AMME', max_length=5),
        ),
        migrations.AlterField(
            model_name='standard',
            name='q2_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AEEM', 'AEEM')], default='AMME', max_length=5),
        ),
        migrations.AlterField(
            model_name='standard',
            name='q3_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AEEM', 'AEEM')], default='AMME', max_length=5),
        ),
    ]
