# Generated by Django 4.2.7 on 2023-11-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0004_alter_standard_q1_type_alter_standard_q2_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='paper_standard', to='marking.standard'),
        ),
    ]
