# Generated by Django 4.2.7 on 2023-12-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0005_paper_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='q1_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AEEM', 'AEEM'), ('AMMEE', 'AMMEE')], default='AMME', max_length=5),
        ),
        migrations.AlterField(
            model_name='standard',
            name='q2_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AEEM', 'AEEM'), ('AMMEE', 'AMMEE')], default='AMME', max_length=5),
        ),
        migrations.AlterField(
            model_name='standard',
            name='q3_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AEEM', 'AEEM'), ('AMMEE', 'AMMEE')], default='AMME', max_length=5),
        ),
    ]
