# Generated by Django 4.2.7 on 2024-01-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0007_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='grades_eenn',
            field=models.CharField(default='M6', max_length=2),
        ),
        migrations.AlterField(
            model_name='total',
            name='grades_emaa',
            field=models.CharField(default='E7', max_length=2),
        ),
        migrations.AlterField(
            model_name='total',
            name='grades_emma',
            field=models.CharField(default='E7', max_length=2),
        ),
        migrations.AlterField(
            model_name='total',
            name='grades_emmn',
            field=models.CharField(default='E7', max_length=2),
        ),
    ]
