# Generated by Django 4.2.7 on 2024-11-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0009_alter_standard_q1_type_alter_standard_q2_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='grades_eeea',
            field=models.CharField(default='E8', max_length=2),
        ),
        migrations.AddField(
            model_name='total',
            name='grades_eeem',
            field=models.CharField(default='E8', max_length=2),
        ),
        migrations.AddField(
            model_name='total',
            name='grades_eeen',
            field=models.CharField(default='E8', max_length=2),
        ),
        migrations.AddField(
            model_name='total',
            name='grades_mmmm',
            field=models.CharField(default='M6', max_length=2),
        ),
    ]
