# Generated by Django 4.2.7 on 2024-11-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0011_total_grades_emmm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='q1_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AEEM', 'AEEM'), ('AMMEE', 'AMMEE'), ('MEEE', 'MEEE'), ('AAEE', 'AAEE')], default='AMME', max_length=5),
        ),
        migrations.AlterField(
            model_name='standard',
            name='q2_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AEEM', 'AEEM'), ('AMMEE', 'AMMEE'), ('MEEE', 'MEEE'), ('AAEE', 'AAEE')], default='AMME', max_length=5),
        ),
        migrations.AlterField(
            model_name='standard',
            name='q3_type',
            field=models.CharField(choices=[('AMME', 'AMME'), ('AMEE', 'AMEE'), ('AEME', 'AEME'), ('AEEM', 'AEEM'), ('AMMEE', 'AMMEE'), ('MEEE', 'MEEE'), ('AAEE', 'AAEE')], default='AMME', max_length=5),
        ),
    ]
